/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import dto.InvoiceDTO;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import java.util.logging.Logger;
import org.apache.log4j.spi.LoggerFactory;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import services.ProductCetagotyService;
import services.InvoiceService;
import services.SupplierService;

/**
 *
 * @author monieuzzaman
 */
public class InvoicesReportPanel extends javax.swing.JPanel {

    private ProductCetagotyService cetagotyService;
    private InvoiceService invoiceService;
    private SupplierService supplierService;
    private Logger log = Logger.getLogger(InvoicesReportPanel.class.getName());

    public InvoicesReportPanel() {
        initComponents();

        // Object Create
        cetagotyService = new ProductCetagotyService();
        invoiceService = new InvoiceService();
        supplierService = new SupplierService();

        // Default Config
        AutoCompleteDecorator.decorate(shopOrCustomersComboBox);
        AutoCompleteDecorator.decorate(invoiceNoComboBox);
        isPurchase.setSelected(true);
        isSell.setSelected(true);

        //Add Invoice List in Combobox
        setInvoiceViaRedioButLogic();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        shopOrCustomersComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        invoiceNoComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        isPurchase = new javax.swing.JRadioButton();
        isSell = new javax.swing.JRadioButton();

        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(productsTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(210, 216, 222));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBackground(new java.awt.Color(26, 109, 192));

        shopOrCustomersComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Shop/Customer Name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 101, Short.MAX_VALUE))
                    .addComponent(shopOrCustomersComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shopOrCustomersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(38, 215, 49));

        invoiceNoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Invoice No");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(invoiceNoComboBox, 0, 290, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invoiceNoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(128, 10, 45));

        isPurchase.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        isPurchase.setForeground(new java.awt.Color(254, 254, 254));
        isPurchase.setText("Purchase Products");
        isPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isPurchaseActionPerformed(evt);
            }
        });

        isSell.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        isSell.setForeground(new java.awt.Color(254, 254, 254));
        isSell.setText("Sell Products");
        isSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isSellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(isPurchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(isSell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isPurchase, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isSell)
                .addContainerGap())
        );

        jPanel2.add(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void isPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isPurchaseActionPerformed
        setInvoiceViaRedioButLogic();
    }//GEN-LAST:event_isPurchaseActionPerformed

    private void isSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isSellActionPerformed
        setInvoiceViaRedioButLogic();
    }//GEN-LAST:event_isSellActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> invoiceNoComboBox;
    private javax.swing.JRadioButton isPurchase;
    private javax.swing.JRadioButton isSell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productsTable;
    private javax.swing.JComboBox<String> shopOrCustomersComboBox;
    // End of variables declaration//GEN-END:variables

    private void setInvoiceViaRedioButLogic() {
        shopOrCustomersComboBox.removeAllItems();
        shopOrCustomersComboBox.addItem("Select");
        if (isPurchase.isSelected()) {
            log.info("Purchase Selected");
            invoiceService.getInvoiceList().forEach(invoice
                    -> shopOrCustomersComboBox.addItem(supplierService.getSupplierDetaisById(invoice.getSupplierId()).getName()));
        }
        if (isSell.isSelected()) {
            log.info("Sell Selected");
            //TODO: Sell logic implement here
            invoiceService.getInvoiceList().forEach(invoice -> shopOrCustomersComboBox.addItem(String.valueOf(invoice.getInvoiceId())));
        }

        shopOrCustomersComboBox.addItemListener(new ItemListener() {

            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    String name = shopOrCustomersComboBox.getSelectedItem().toString();

                    log.info("Customer Name: " + name);
                    addInvoiceNoInCombox(supplierService.getByName(name).getId());

                }
            }
        });
    }

    public void addInvoiceNoInCombox(int supplierId) {
        //Add Product Name in Combobox
        invoiceNoComboBox.removeAllItems();
        invoiceNoComboBox.addItem("Select");
        invoiceService.getInvoiceListBySupplierId(supplierId).forEach(invoice
                -> invoiceNoComboBox.addItem(String.valueOf(invoice.getInvoiceId()))
        );

        invoiceNoComboBox.addItemListener(new ItemListener() {

            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    String invoiceNo = invoiceNoComboBox.getSelectedItem().toString();
                    showInvoiceInTableByInvoiceNO(invoiceNo);

                }
            }

            private void showInvoiceInTableByInvoiceNO(String invoiceNo) {
                log.info("Searching invoice List By " + invoiceNo + " for table show");
                List<InvoiceDTO> invoiceDTOs = invoiceService.getInvoiceListByInvoiceNo(invoiceNo);
                log.info("Getting Result "+invoiceDTOs);
            }
        });
    }
}
